name: "al_pulse"
version: "1.0.0"
profile: al_pulse

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-start: # SQL statements to run at the start of a dbt run
  - "{{ register_macros() }}"
  - SET preserve_insertion_order = FALSE
  - SET memory_limit = '6GB'
  - PRAGMA temp_directory = '/tmp'
  - PRAGMA max_temp_directory_size = '20GB'
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  al_pulse:
    staging:
      +materialized: ephemeral
    marts:
      +materialized: table
    intermediate:
      +materialized: ephemeral

seeds:
  al_pulse:
    +column_types: # event_date,event_name,description
      event_date: date
      event_name: text
      description: text

vars:
  metrics:
    c: normal
    al_per_1000: normal
    num_guests: average
    num_rooms: average
    is_building_post_1951: pcnt
    rooms_0: pcnt
    rooms_1: pcnt
    rooms_2: pcnt
    rooms_3: pcnt
    rooms_more_than_3: pcnt
    is_moradia: pcnt
    is_apartamento: pcnt
    lost_licenses: normal

